//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Janitor {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Janitor.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instances of classes implementing System.IDisposable interface should always be disposed properly by calling Dispose() method or be used within a Using block statement..
        /// </summary>
        internal static string MissingDisposeAnalyzerDescription {
            get {
                return ResourceManager.GetString("MissingDisposeAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object name &apos;{0}&apos; not diposed properly..
        /// </summary>
        internal static string MissingDisposeAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MissingDisposeAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object not disposed properly..
        /// </summary>
        internal static string MissingDisposeAnalyzerTitle {
            get {
                return ResourceManager.GetString("MissingDisposeAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code block is not completely covered with a Try-Catch statement. This notfication is not shown for code blocks being either in Catch or Finally statements..
        /// </summary>
        internal static string MissingTryCatchAnalyzerDescription {
            get {
                return ResourceManager.GetString("MissingTryCatchAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code block is not covered with a Try-Catch statement..
        /// </summary>
        internal static string MissingTryCatchAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MissingTryCatchAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code block is not covered with a Try-Catch statement..
        /// </summary>
        internal static string MissingTryCatchAnalyzerTitle {
            get {
                return ResourceManager.GetString("MissingTryCatchAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression syntax. For more information on Microsoft .NET regular expressions, visit https://msdn.microsoft.com/en-us/library/hs600312.aspx .
        /// </summary>
        internal static string RegularExpressionAnalyzerDescription {
            get {
                return ResourceManager.GetString("RegularExpressionAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression syntax: {0}..
        /// </summary>
        internal static string RegularExpressionAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("RegularExpressionAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression syntax..
        /// </summary>
        internal static string RegularExpressionAnalyzerTitle {
            get {
                return ResourceManager.GetString("RegularExpressionAnalyzerTitle", resourceCulture);
            }
        }
    }
}
